### PR TITLE
Fix 57

### LINKED ISSUE #57: Add tracking data in plugin: Settings, admin choice and data tracking
**Describe the bug**
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

This exercise is needed to ensure we're collecting all the relevant data (with regards to the all features added ) and utilizing the data to its fullest potential.

**Additional context**
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

### PR DESCRIPTION
**Pull request by PratapDungrani**
Fixed, Add tracking data in plugin: Settings, admin choice and data tracking.

Fix #57

### CODE REVIEW

File: includes/class-alg-wc-cpp-tracking.php [hunk 1]
```diff
@@ -0,0 +1,186 @@
+<?php // phpcs:ignore
```
Comment (handelce) [inline includes/class-alg-wc-cpp-tracking.php:1]: @PratapDungrani As per WP standard, the class file names should be based on the class name.

**Review by handelce — CHANGES_REQUESTED** [review]

**Review by handelce — APPROVED** [review]
